### ISSUE TITLE
Lens errors

### ISSUE THREAD

**Issue by VoxelCreatesStuff** [TTT-2/ttt2-role_snif#13]
The lens can only be flipped up for a seconds. Im assuming it should stay up if you hold down left click?

Also the console prints this error

[[TTT2] Sniffer [ROLE]] gamemodes/terrortown/entities/weapons/weapon_ttt2_lens.lua:109: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. CanSeeFootsteps - gamemodes/terrortown/entities/weapons/weapon_ttt2_lens.lua:109
    3. fn - gamemodes/terrortown/entities/weapons/weapon_ttt2_lens.lua:258
     4. unknown - lua/ulib/shared/hook.lua:109

**Comment by TimGoll** [comment]
thanks for the report, I haven't touched the sniffer in years probably

**Comment by TimGoll** [comment]
well it is the same as #12, so I'll close this one, somehow we all missed that
